routes/web.php
<?php

use App\Http\Controllers\Admin\AccountController;
use App\Http\Controllers\Admin\AdresseEntrepriseController;
use App\Http\Controllers\Admin\CostCenterController;
use App\Http\Controllers\Admin\EntrepriseController;
use App\Http\Controllers\Admin\LocalisationController;
use App\Http\Controllers\Admin\PassagerController;
use App\Http\Controllers\Admin\PasswordController;
use App\Http\Controllers\Admin\PiloteController;
use App\Http\Controllers\Admin\TypeFacturationController;
use App\Http\Controllers\AdresseReservationController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\ReservationController;
use App\Http\Livewire\Account\AccountForm;
use App\Http\Livewire\Account\EditPasswordForm;
use App\Http\Livewire\Account\Form;
use App\Http\Livewire\AdresseReservation\AdresseReservationForm;
use App\Http\Livewire\Auth\ForgotPasswordForm;
use App\Http\Livewire\CostCenter\CostCenterForm;
use App\Http\Livewire\Entreprise\AdresseEntrepriseForm;
use App\Http\Livewire\Entreprise\EntrepriseForm;
use App\Http\Livewire\Localisation\LocalisationForm;
use App\Http\Livewire\Passager\PassagerForm;
use App\Http\Livewire\Pilote\PiloteForm;
use App\Http\Livewire\Pilote\RecapReservationPilote;
use App\Http\Livewire\Reservation\ReservationForm;
use App\Http\Livewire\ReservationEdit;
use App\Http\Livewire\Reservation\ReservationShow;
use App\Http\Livewire\TypeFacturation\TypeFacturationForm;
use App\Mail\AdminReservationConfirmed;
use App\Models\AdresseReservation;
use App\Models\Localisation;
use App\Models\Passager;
use App\Models\Reservation;
use Illuminate\Contracts\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome', [
        'reservations_to_confirm' => Reservation::toConfirmed()->count(),
        'reservations' => Reservation::count()
    ]);
})->name('homepage');

Route::get('/login', function () {
    return view('welcome');
})->name('login.form');

Route::post('/login', [LoginController::class, 'authenticate'])
    ->name('login');
Route::get('/logout', [LoginController::class, 'logout'])
    ->name('logout');

Route::middleware('guest')->group(function () {
    Route::get('/forgot-password', ForgotPasswordForm::class)
        ->name('password.request');

    Route::get('/reset-password/{token}', [LoginController::class, 'resetPasswordEdit'])
        ->name('password.reset');

    Route::post('/reset-password', [LoginController::class, 'resetPassword'])
        ->name('password.update');
});

Route::prefix('/admin')->middleware('auth')->name('admin.')->group(function () {

    Route::get('/accounts/{account}/password/edit', EditPasswordForm::class)
        ->name('accounts.password.edit');

    // ACCOUNTS
    Route::get('accounts/create', AccountForm::class)
        ->name('accounts.create');
    Route::get('accounts/{account}/edit', AccountForm::class)
        ->name('accounts.edit');
    Route::resource('accounts', AccountController::class)
        ->except(['show', 'create', 'store', 'edit', 'update']);

    // ENTREPRISE
    Route::get('entreprises/create', EntrepriseForm::class)
        ->name('entreprises.create');
    Route::get('entreprises/{entreprise}/edit', EntrepriseForm::class)
        ->name('entreprises.edit');
    Route::resource('entreprises', EntrepriseController::class)
        ->except('create', 'store', 'edit', 'update');

    // ADRESSE ENTREPRISE
    Route::get('entreprises/{entreprise}/adresses/create', AdresseEntrepriseForm::class)
        ->name('entreprises.adresses.create');
    Route::get('entreprises/{entreprise}/adresses/{adress}/edit', AdresseEntrepriseForm::class)
        ->name('entreprises.adresses.edit');
    Route::resource('entreprises.adresses', AdresseEntrepriseController::class)
        ->except(['show', 'create', 'store', 'edit', 'update']);

    // PASSAGER
    Route::get('passagers/create', PassagerForm::class)->name('passagers.create');
    Route::get('passagers/{passager}/edit', PassagerForm::class)->name('passagers.edit');
    Route::resource('passagers', PassagerController::class)
        ->except(['show', 'create', 'store', 'edit', 'update']);

    // PILOTE
    Route::get('pilotes/create', PiloteForm::class)
        ->name('pilotes.create');
    Route::get('pilotes/{pilote}/edit', PiloteForm::class)
        ->name('pilotes.edit');
    Route::get('pilotes/{pilote}/recap-reservation', RecapReservationPilote::class)
        ->name('pilotes.recap-reservation');
    Route::resource('pilotes', PiloteController::class)
        ->except(['show', 'create', 'store', 'edit', 'update']);

    // LOCALISATION
    Route::get('localisations/create', LocalisationForm::class)
        ->name('localisations.create');
    Route::get('localisations/{localisation}/edit', LocalisationForm::class)
        ->name('localisations.edit');
    Route::resource('localisations', LocalisationController::class)
        ->except(['show', 'create', 'store', 'edit', 'update']);

    // COST CENTER
    Route::get('costcenter/create', CostCenterForm::class)->name('costcenter.create');
    Route::get('costcenter/{costCenter}/edit', CostCenterForm::class)->name('costcenter.edit');
    Route::resource('costcenter', CostCenterController::class)
        ->except(['show', 'create', 'store', 'edit', 'update']);

    // TYPE FACTURATION
    Route::get('typefacturation/create', TypeFacturationForm::class)
        ->name('typefacturation.create');
    Route::get('typefacturation/{typefacturation}/edit', TypeFacturationForm::class)
        ->name('typefacturation.edit');
    Route::resource('typefacturation', TypeFacturationController::class)
        ->except(['show', 'create', 'store', 'edit', 'update']);

    // ADRESSE RESERVATION
    Route::get('adresse-reservation/create', AdresseReservationForm::class)
        ->name('adresse-reservation.create');
    Route::get('adresse-reservation/{adresseReservation}/edit', AdresseReservationForm::class)
        ->name('adresse-reservation.edit');
    Route::resource('adresse-reservation', AdresseReservationController::class)
        ->except(['show', 'create', 'store', 'edit', 'update']);

    // RESERVATION
    Route::get('reservations/show/{reservation}', ReservationShow::class)
        ->name('reservations.show');
    Route::get('reservations/create', ReservationForm::class)
        ->name('reservations.create');
    Route::get('reservations/{reservation}/edit', ReservationForm::class)
        ->name('reservations.edit');
    Route::resource('reservations', ReservationController::class)
        ->except(['show', 'update', 'destroy', 'edit', 'create', 'store']);
});

Route::prefix('/admin/select')->group(function () {

    // API PASSAGER
    Route::get('/passagers', function (Request $request){
        $search = $request->input('search');
        $selected = $request->input('selected');
        $user = $request->input('user');

        $result = Passager::query()
            ->select('id', 'nom', 'email');

        if (!empty($user)) {
            $result->where('user_id', '=', (int)$user);
        }

        $result->when($search, function (Builder $query, $search) {
            $query->where('nom', 'like', "%{$search}%");
        })->when(
                $selected,
                function (Builder $query, $selected) {
                    $query->whereIn('id', $selected);
                }
            );

        return $result->get();
    })->name('admin.api.passagers');

    // API LOCALISATION
    Route::get('/pickup_place', function (Request $request) {
        $search = $request->input('search');
        $selected = $request->input('selected');

        return Localisation::query()
            ->select('id', 'nom')
            ->orderBy('nom')
            ->when($search, function (Builder $query, $search) {
                $query->where('nom', 'like', "%{$search}%");
            })
            ->when(
                $selected,
                function (Builder $query, $selected) {
                    $query->whereIn('id', $selected);
                }
            )
            ->get();
    })->name('admin.api.pickupplace');

    // API ADRESSE RESERVATION
    Route::get('/adresses', function (Request $request) {
        $search = $request->input('search');
        $selected = $request->input('selected');

        return AdresseReservation::query()
            ->select('id', 'adresse')
            ->orderBy('adresse')
            ->when($search, function (Builder $query, $search) {
                $query->where('adresse', 'like', "%{$search}%");
            })
            ->when(
                $selected,
                function (Builder $query, $selected) {
                    $query->whereIn('id', $selected);
                }
            )
            ->get();
    })->name('admin.api.adresses');
});

Route::get('/mailable', function () {
    return new AdminReservationConfirmed(Reservation::find(1));
});

app/Http/Controllers/Admin/PiloteController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Pilote;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class PiloteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        return view('admin.pilotes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Pilote $pilote
     * @return RedirectResponse
     */
    public function destroy(Pilote $pilote)
    {
        $pilote->delete();
        return redirect()
            ->route('admin.pilotes.index')
            ->with('success', "Le pilote a bien été supprimé.");
    }
}

app/Http/Livewire/Account/AccountForm.php
<?php

namespace App\Http\Livewire\Account;

use App\Models\Entreprise;
use App\Models\User;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Hash;
use Livewire\Component;
use WireUi\Traits\Actions;

class AccountForm extends Component
{
    use Actions;

    public User $user;

    public function mount(User $account)
    {
        $this->user = $account;

        if (!$this->user->exists) {
            $this->user->is_actif = false;
            $this->user->is_admin_ardian = false;
        }
    }

    protected function getRules()
    {
        $rules = [
            'user.nom' => 'required',
            'user.prenom' => 'required',
            'user.telephone' => 'required',
            'user.adresse' => 'required',
            'user.adresse_bis' => 'nullable',
            'user.code_postal' => 'required',
            'user.ville' => 'required',
            'user.entreprise_id' => 'required',
            'user.is_admin_ardian' => 'boolean',
            'user.is_actif' => 'boolean',
        ];

        if ($this->user->exists) {
            $rules['user.email'] = 'required|email';
        } else {
            $rules['user.email'] = 'required|email|unique:users,email';
        }

        return $rules;
    }

    protected function getValidationAttributes()
    {
        return [
            'user.entreprise_id' => 'entreprise'
        ];
    }

    public function render()
    {
        return view('livewire.account.account-form')
            ->layout('components.admin-layout')
        ;
    }

    public function save()
    {
        $this->validate();

        try {
            if ($this->user->exists) {
                $this->user->update();
                $this->notification()->success(
                    $title = 'Compte modifié',
                    $description = 'Le compte a bien été modifié'
                );
                $this->reset(['user.nom']);
            } else {
                $this->user->password = Hash::make('test');
                $this->user->save();
                $this->notification()->success(
                    $title = 'Compte créé',
                    $description = 'Le compte a bien été créé'
                );
            }
        } catch (\Exception $exception) {
            if (App::environment(['local'])) {
                ray([
                    'user' => $this->user
                ])->exception($exception);
            }
            // TODO Sentry en production
        }
    }
}

app/Http/Livewire/Account/EditPasswordForm.php
<?php

namespace App\Http\Livewire\Account;

use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Livewire\Component;

class EditPasswordForm extends Component
{
    public User $user;
    public string $password = '';

    public function mount(User $account)
    {
        $this->user = $account;
    }

    public function render()
    {
        return view('livewire.account.edit-password-form')
            ->layout('components.admin-layout');
    }

    protected function getRules()
    {
        return [
            'password' => 'required|current_password:web'
        ];
    }

    protected function getValidationAttributes()
    {
        return [
            'password' => 'mot de passe'
        ];
    }

    public function editAction()
    {
        $this->validate();

        $this->user->update([
            'password' => Hash::make($this->password)
        ]);
    }
}

app/Http/Livewire/Account/UsersDataTable.php
<?php

namespace App\Http\Livewire\Account;

use App\Models\User;
use App\Traits\WithSorting;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Livewire\Component;
use Livewire\WithPagination;
use MeiliSearch\Endpoints\Indexes;

class UsersDataTable extends Component
{
    use WithPagination, WithSorting;

    public int $perPage = 6;
    public string $search = '';
    public string $sortField = 'nom';

    /**
     * @return Application|Factory|View
     */
    public function render(): View|Factory|Application
    {
        return view('livewire.account.users-data-table', [
            'users' => User::search($this->search, function (Indexes $melisearch, string $query, array $options) {
                $sort = [$this->sortField.':'.$this->sortDirection];
                $options['sort'] = $sort;
                return $melisearch->search($query, $options);
            }) // @phpstan-ignore-line
                ->orderBy($this->sortField, $this->sortDirection)
                ->paginate($this->perPage)
        ]);
    }
}

app/Http/Livewire/AdresseReservation/AdresseReservationForm.php
<?php

namespace App\Http\Livewire\AdresseReservation;

use App\Models\AdresseReservation;
use Illuminate\Support\Facades\App;
use Livewire\Component;
use WireUi\Traits\Actions;

class AdresseReservationForm extends Component
{
    use Actions;

    public AdresseReservation $adresseReservation;

    public function mount(AdresseReservation $adresseReservation)
    {
        $this->adresseReservation = $adresseReservation;
    }

    public function render()
    {
        return view('livewire.adresse-reservation.adresse-reservation-form')
            ->layout('components.admin-layout');
    }

    protected function getRules()
    {
        return [
            'adresseReservation.adresse' => 'required',
            'adresseReservation.adresse_complement' => 'nullable',
            'adresseReservation.code_postal' => 'required',
            'adresseReservation.ville' => 'required',
            'adresseReservation.user_id' => 'required',
        ];
    }

    public function save()
    {
        $this->validate();

        try {
            if ($this->adresseReservation->exists) {
                $this->adresseReservation->update();
                $this->notification()->success("Adresse modifiée", "L'adresse a bien été modifée.");
            } else {
                $this->adresseReservation->save();
                $this->notification()->success("Adresse créée", "L'adresse a bien été créée.");
                $this->adresseReservation = new AdresseReservation();
            }
        }catch (\Exception $exception) {
            $this->notification()->error(
                "Erreur pendant le traitement",
                "Une erreur est survenue pendant le traitement"
            );
            if (App::environment(['local'])) {
                ray([
                    'adresse_reservation' => $this->adresseReservation
                ])->exception($exception);
            }
            // TODO Sentry en production
        }
    }
}

app/Http/Livewire/CostCenter/CostCenterDataTable.php
<?php

namespace App\Http\Livewire\CostCenter;

use App\Models\CostCenter;
use App\Traits\WithSorting;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Livewire\Component;
use Livewire\WithPagination;

class CostCenterDataTable extends Component
{
    use WithPagination, WithSorting;

    public string $search = '';
    public string $sortField = 'nom';
    public int $perPage = 10;

    /**
     * @return Application|Factory|View
     */
    public function render(): View|Factory|Application
    {
        return view('livewire.cost-center.cost-center-data-table', [
            'costcenters' => CostCenter::search($this->search) // @phpstan-ignore-line
                ->orderBy($this->sortField, $this->sortDirection)
                ->paginate($this->perPage)
        ]);
    }
}

resources/views/livewire/pilote/pilote-data-table.blade.php
<div>
    <x-admin.content>
        <x-datatable.search wire:model="search"/>
        <x-datatable>
            <x-slot name="headers">
                <tr>
                    <x-datatable.th sortable wire:click="sortBy('nom')" :direction="$sortDirection">Nom</x-datatable.th>
                    <x-datatable.th sortable wire:click="sortBy('prenom')" :direction="$sortDirection">Prénom
                    </x-datatable.th>
                    <x-datatable.th sortable wire:click="sortBy('email')" :direction="$sortDirection">Email
                    </x-datatable.th>
                    <x-datatable.th>Téléphone</x-datatable.th>
                    <x-datatable.th sortable wire:click="sortBy('adresse')" :direction="$sortDirection">Adresse
                    </x-datatable.th>
                    <x-datatable.th>Actions</x-datatable.th>
                </tr>
            </x-slot>
            <x-slot name="body">
                @forelse($pilotes as $pilote)
                    <x-datatable.tr>
                        <x-datatable.td>{{ $pilote->nom }}</x-datatable.td>
                        <x-datatable.td>{{ $pilote->prenom }}</x-datatable.td>
                        <x-datatable.td>{{ $pilote->email }}</x-datatable.td>
                        <x-datatable.td>{{ $pilote->telephone }}</x-datatable.td>
                        <x-datatable.td>{{ $pilote->adresse }}</x-datatable.td>
                        <x-datatable.td>
                            <x-dropdown>
                                <x-slot name="trigger">
                                    <x-button label="Actions" info sm/>
                                </x-slot>

                                <x-dropdown.item label="Éditer"
                                                 href="{{ route('admin.pilotes.edit', ['pilote' => $pilote->id]) }}"/>
                                <x-dropdown.item label="Récap. des courses"
                                                 href="{{ route('admin.pilotes.recap-reservation', ['pilote' => $pilote->id]) }}"/>
                                <x-dropdown.item separator
                                                 href="{{ route('admin.pilotes.destroy', ['pilote' => $pilote->id]) }}">
                                    <div class="text-red-500">Supprimer</div>
                                </x-dropdown.item>
                            </x-dropdown>
                        </x-datatable.td>
                    </x-datatable.tr>
                @empty
                    <x-datatable.tr>
                        <x-datatable.td class="text-center" colspan="6">Aucun pilote</x-datatable.td>
                    </x-datatable.tr>
                @endforelse
            </x-slot>
            <x-slot name="tfoot">
            </x-slot>
        </x-datatable>
        <div class="mt-4 px-1">
            {{ $pilotes->links('components.datatable.pagination') }}
        </div>
    </x-admin.content>
</div>

resources/views/livewire/pilote/pilote-form.blade.php
<div>
    <x-title-section>
        <x-slot:title>
            {!! $pilote->exists ? "Modification du pilote <span class='text-blue-500'>".$pilote->full_name."</span>" : "Création d'un piloe" !!}
        </x-slot:title>
    </x-title-section>
    <x-admin.content>
        <form wire:submit.prevent="save">
            <div class="form-group">
                <x-input label="Nom" wire:model.defer="pilote.nom" />
            </div>
            <div class="form-group">
                <x-input label="Prénom" wire:model.defer="pilote.prenom" />
            </div>
            <div class="form-group">
                <x-input label="Téléphone" wire:model.defer="pilote.telephone" />
            </div>
            <div class="form-group">
                <x-input label="Adresse email" wire:model.defer="pilote.email" type="email"/>
            </div>
            <div class="form-group">
                <x-input label="Nom de l'entreprise" wire:model.defer="pilote.entreprise" />
            </div>
            <div class="form-group">
                <x-input label="adresse" wire:model.defer="pilote.adresse" />
            </div>
            <div class="form-group">
                <x-input label="Adresse complément" wire:model.defer="pilote.adresse_complement" />
            </div>
            <div class="form-group">
                <x-input label="Code postal" wire:model.defer="pilote.code_postal" />
            </div>
            <div class="form-group">
                <x-input label="Ville" wire:model.defer="pilote.ville" />
            </div>
            <div class="mt-5">
                <x-button type="submit" label="Enregistrer" info />
            </div>
        </form>
    </x-admin.content>
</div>

resources/views/livewire/pilote/recap-reservation-pilote.blade.php
<div>
    <x-title-section>
        <x-slot:title>
            Liste des courses du pilote <span class="text-blue-500">{{ $pilote->full_name }}</span>
        </x-slot:title>
    </x-title-section>
    <x-admin.content>
        <div class="text-2xl">Liste des réservations</div>
        <div class="py-3 border-b border-gray-400 flex justify-between items-end">
            <div class="space-x-4 flex">
                <x-datetime-picker
                    without-time
                    without-timezone
                    label="Date de début"
                    placeholder="Date de début"
                    wire:model="dateDebut"
                />
                <x-datetime-picker
                    without-time
                    without-timezone
                    label="Date de fin"
                    placeholder="Date de fin"
                    wire:model="dateFin"
                />
            </div>
            <div>
                <x-button label="Exporter"/>
            </div>
        </div>
        <x-datatable>
            <x-slot name="headers">
                <tr>
                    <x-datatable.th>Référence</x-datatable.th>
                    <x-datatable.th>Entreprise</x-datatable.th>
                    <x-datatable.th>Date</x-datatable.th>
                    <x-datatable.th>Client</x-datatable.th>
                    <x-datatable.th>Validation</x-datatable.th>
                    <x-datatable.th>Tarif</x-datatable.th>
                    <x-datatable.th>Majoration</x-datatable.th>
                    <x-datatable.th>Encaisse</x-datatable.th>
                    <x-datatable.th>Encompte</x-datatable.th>
                    <x-datatable.th>Action</x-datatable.th>
                </tr>
            </x-slot>
            <x-slot name="body">
                @forelse($reservations as $reservation)
                    <x-datatable.tr>
                        <x-datatable.td>
                            <span class="text-blue-500" data-tooltip-target="tooltip-left{{ $reservation->id }}"
                                  data-tooltip-placement="top">{{ $reservation->reference }}</span>

                            <div id="tooltip-left{{ $reservation->id }}" role="tooltip"
                                 class="shadow-xl transition-opacity duration-300 inline-block absolute invisible z-10 py-2 px-3 text-sm font-medium text-white bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip dark:bg-gray-700">
                                <dl>
                                    <dt>Départ</dt>
                                    <dd>{{ $reservation->display_from }}</dd>

                                    <div class="mt-3">
                                        <dt>Arrivée</dt>
                                        <dd>{{ $reservation->display_to }}</dd>
                                    </div>

                                    <div class="mt-2">
                                        <dt>Commentaire</dt>
                                        <dd>{{ $reservation->comment }}</dd>
                                    </div>
                                </dl>
                                <div class="tooltip-arrow" data-popper-arrow></div>
                            </div>
                        </x-datatable.td>
                        <x-datatable.td>{{ $reservation->passager->user->entreprise->nom }}</x-datatable.td>
                        <x-datatable.td>{{ $reservation->pickup_date->format('d/m/Y H:i') }}</x-datatable.td>
                        <x-datatable.td>{{ $reservation->passager->user->full_name }}</x-datatable.td>
                        <x-datatable.td>
                            XXXX €
                        </x-datatable.td>
                        <x-datatable.td>
                            <x-input placeholder="Tarif" right-icon="currency-euro" form="form{{ $reservation->id }}"/>
                        </x-datatable.td>
                        <x-datatable.td>
                            <x-input placeholder="Majoration en %"/>
                        </x-datatable.td>
                        <x-datatable.td>
                            <x-input placeholder="Encaisse"/>
                        </x-datatable.td>
                        <x-datatable.td>
                            <x-input placeholder="Encompte" right-icon="currency-euro"/>
                        </x-datatable.td>
                        <x-datatable.td>
                            <form action="" id="form{{ $reservation->id }}">
                                <x-button label="Valider" info sm/>
                            </form>
                        </x-datatable.td>
                    </x-datatable.tr>
                @empty
                    <x-datatable.tr>
                        <x-datatable.td class="text-center" colspan="6">Aucune réservation</x-datatable.td>
                    </x-datatable.tr>
                @endforelse
            </x-slot>
            <x-slot name="tfoot">
            </x-slot>
        </x-datatable>
        <div class="mt-4 px-1">
            {{ $reservations->links('components.datatable.pagination') }}
        </div>
    </x-admin.content>
</div>